[phases.setup]
nixPkgs = [
  "nodejs",
  "chromium",
  "glib",
  "nss",
  "atk",
  "cups",
  "dbus",
  "libdrm",
  "gtk3",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "alsa-lib"
]

[phases.build]
cmds = [
  "npm install",
  "npx puppeteer browsers install chrome --no-prompt"   # Fuerza instalaci√≥n de Chromium compatible
]

[start]
cmd = "node bot.js"