[phases.setup]
nixPkgs = ["nodejs", "chromium", "glib", "nss", "atk", "cups", "libdrm", "libxcb", "libX11", "libXcomposite", "libXdamage", "libXext", "libXfixes", "libXrandr", "mesa"]

[phases.build]
cmds = ["npm install"]